server:
  port: 8082

spring:
  application:
    name: order-service
#  main:
#    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  circuitbreaker:
    enabled: true

  okhttp:
    enabled: true

#  httpclient:
#    connection-timeout: 10
#    connection-timer-repeat: 10
  client:
    refresh-enabled: true
    config:
      default:
        connectTimeout: 5000 #单位毫秒
        readTimeout: 20000 #单位毫秒


